# Generated by Django 4.0.5 on 2022-07-01 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvan',
            name='added',
            field=models.ForeignKey(help_text='Who Added This Carvan?', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='Added By'),
        ),
        migrations.AlterField(
            model_name='carvan',
            name='cleanguy',
            field=models.ForeignKey(help_text='Select any clean guy', limit_choices_to={'is_emp': True, 'is_self': True, 'type': 'Cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner', to=settings.AUTH_USER_MODEL, verbose_name='Cleaning Guy'),
        ),
    ]
