# Generated by Django 4.0.5 on 2022-07-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_carvan_added_alter_carvan_cleanguy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carvan',
            old_name='cleanguy',
            new_name='cleaningguy',
        ),
    ]
