# Generated by Django 4.0.5 on 2022-07-01 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_rename_cleanguy_carvan_cleaningguy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvan',
            name='cleaningguy',
            field=models.ForeignKey(help_text='Select any clean guy', limit_choices_to={'type': 'Cleaner'}, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner', to=settings.AUTH_USER_MODEL, verbose_name='Cleaning Guy'),
        ),
        migrations.AlterField(
            model_name='carvan',
            name='washingguy',
            field=models.ForeignKey(help_text='Select any washing guy', limit_choices_to={'type': 'Washer'}, on_delete=django.db.models.deletion.CASCADE, related_name='washer', to=settings.AUTH_USER_MODEL, verbose_name='Washing Guy'),
        ),
    ]
