# Generated by Django 4.0.5 on 2022-07-01 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_alter_carvan_cleaningguy_alter_carvan_washingguy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carvan',
            name='cleaningguy',
            field=models.ForeignKey(help_text='Select any clean guy', limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner', to=settings.AUTH_USER_MODEL, verbose_name='Cleaning Guy'),
        ),
        migrations.AlterField(
            model_name='carvan',
            name='washingguy',
            field=models.ForeignKey(help_text='Select any washing guy', limit_choices_to={'is_superuser': False}, on_delete=django.db.models.deletion.CASCADE, related_name='washer', to=settings.AUTH_USER_MODEL, verbose_name='Washing Guy'),
        ),
        migrations.CreateModel(
            name='CARVANSTATUS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning', models.BooleanField(default=False, help_text='Cleaning Status', verbose_name='Cleaning')),
                ('washing', models.BooleanField(default=False, help_text='Washing Status', verbose_name='Washing')),
                ('complete', models.BooleanField(default=False, help_text='Complete Status', verbose_name='Complete')),
                ('carvan', models.OneToOneField(help_text='Select any carvan', on_delete=django.db.models.deletion.CASCADE, to='app.carvan', verbose_name='Carvan')),
            ],
        ),
    ]
