# Generated by Django 4.0.5 on 2022-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_carvan_cleaningguy_alter_carvan_washingguy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvanstatus',
            name='cleaning_required',
            field=models.BooleanField(default=False, help_text='Is cleaning required?', verbose_name='Cleaning Required'),
        ),
        migrations.AddField(
            model_name='carvanstatus',
            name='washing_required',
            field=models.BooleanField(default=False, help_text='Is washing required?', verbose_name='Washing Required'),
        ),
        migrations.AlterField(
            model_name='carvanstatus',
            name='cleaning',
            field=models.BooleanField(default=False, help_text='Cleaning Status', verbose_name='Cleaning done'),
        ),
        migrations.AlterField(
            model_name='carvanstatus',
            name='complete',
            field=models.BooleanField(default=False, help_text='Complete Status', verbose_name='Complete done'),
        ),
        migrations.AlterField(
            model_name='carvanstatus',
            name='washing',
            field=models.BooleanField(default=False, help_text='Washing Status', verbose_name='Washing done'),
        ),
    ]
