# Generated by Django 4.0.6 on 2022-07-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_carvanstatus_cleaning_required_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EXTRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Cost of extra', max_digits=256, verbose_name='Cost')),
                ('carvan', models.ForeignKey(help_text='Select any carvan', on_delete=django.db.models.deletion.CASCADE, to='app.carvanstatus', verbose_name='Carvan')),
            ],
        ),
        migrations.CreateModel(
            name='IMAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image of damage', upload_to='images/', verbose_name='Image')),
                ('extra', models.ForeignKey(help_text='Select any extra', on_delete=django.db.models.deletion.CASCADE, to='app.extra', verbose_name='Extra')),
            ],
        ),
    ]
