# Generated by Django 4.0.6 on 2022-07-04 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_extra_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='note',
            field=models.TextField(blank=True, help_text='Note', null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='carvan',
            name='cleaningguy',
            field=models.ForeignKey(blank=True, help_text='Select any clean guy', limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cleaner', to=settings.AUTH_USER_MODEL, verbose_name='Cleaning Guy'),
        ),
        migrations.AlterField(
            model_name='carvan',
            name='washingguy',
            field=models.ForeignKey(blank=True, help_text='Select any washing guy', limit_choices_to={'is_superuser': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='washer', to=settings.AUTH_USER_MODEL, verbose_name='Washing Guy'),
        ),
    ]
