# Generated by Django 4.0.6 on 2022-07-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_extra_note_alter_carvan_cleaningguy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carvan',
            old_name='cleanguynote',
            new_name='cleaningguynote',
        ),
    ]
