# Generated by Django 4.0.5 on 2022-07-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_cleaner',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_washer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='type',
            field=models.CharField(blank=True, choices=[('Cleaner', 'Cleaner'), ('Washer', 'Washer'), ('Manager', 'Manager')], default='', help_text='Which type of this user is?', max_length=254, null=True, verbose_name='Type'),
        ),
    ]
