# Generated by Django 4.0.5 on 2022-07-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_cleaner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Cleaner', 'Cleaner'), ('Washer', 'Washer'), ('Manager', 'Manager')], default='Cleaner', help_text='Which type of this user is?', max_length=254, verbose_name='Type'),
        ),
    ]
